source 'https://rubygems.org'

gem 'rails' # v4.2.5.1 is outdated, causing bundler to fail. all works well with latest version of rails
gem 'sqlite3'

gem 'dotenv-rails'
gem 'shopify_app', '~> 8.0.0'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'

group :development do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
