inherit_gem:
    rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'test/tmp/**/*'
    - 'vendor/bundle/**/*'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - '**/Gemfile'
    - 'test/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

