# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActiveRecord::CollectionCacheKey; end
module ActiveStorage::Blob::Analyzable; end
module ActiveStorage::Blob::Identifiable; end
module ActiveStorage::Variant; end
module ShopifyApp::WebhooksController::ShopifyApp::WebhookVerification; end
