name: Comment on closed Waiting for Response Issues
on:
  issues: 
    types: [closed]
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create Comment
        uses: actions-cool/issues-helper@v3
        if: contains(github.event.issue.labels.*.name, 'Waiting for Response')
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            We are closing this issue because we did not hear back regarding additional details we needed to resolve this issue. If the issue persists and you are able to provide the missing clarification we need, feel free to respond and reopen this issue.

            We appreciate your understanding as we try to manage our number of open issues.